INSERT INTO CLIENTE (NOME, CPF, EMAIL, PASSAPORTE, PAIS_ORIGEM, ENDERECO_PAIS_ORIGEM, DATA_NASCIMENTO, TELEFONE) VALUES ('Felipe Santos', '85908566071', 'felipe@teste.gmail.com', 'BG665764', 'Brasil', 'endereço qualquer no brasil', '1991-05-31','412341234');
INSERT INTO CLIENTE (NOME, CPF, EMAIL, PASSAPORTE, PAIS_ORIGEM, ENDERECO_PAIS_ORIGEM, DATA_NASCIMENTO, TELEFONE) VALUES ('Kassi Mentz', '74490265034', 'kassi@teste.gmail.com', 'IG516215', 'Argentina', 'endereço qualquer na argentina', '1989-04-20','931394858');
INSERT INTO CLIENTE (NOME, CPF, EMAIL, PASSAPORTE, PAIS_ORIGEM, ENDERECO_PAIS_ORIGEM, DATA_NASCIMENTO, TELEFONE) VALUES ('Vitor Hugo', '74664031076', 'vitor@teste.gmail.com', 'BI913814', 'Chile', 'endereço qualquer no chile', '1994-03-28','491394058');
INSERT INTO CLIENTE (NOME, CPF, EMAIL, PASSAPORTE, PAIS_ORIGEM, ENDERECO_PAIS_ORIGEM, DATA_NASCIMENTO, TELEFONE) VALUES ('Leandro Paulino', '91447994035', 'leandro@teste.gmail.com', 'MV807173', 'Uruguai', 'endereço qualquer no uruguai', '1996-09-13','521420943');
INSERT INTO CLIENTE (NOME, CPF, EMAIL, PASSAPORTE, PAIS_ORIGEM, ENDERECO_PAIS_ORIGEM, DATA_NASCIMENTO, TELEFONE) VALUES ('Daniel Santiago', '38978934013', 'daniel@teste.gmail.com', 'HV161043', 'Brasil', 'outro endereço qualquer no brasil', '1989-12-04','938741574');


INSERT INTO ENDERECO (LOGRADOURO, CEP, CIDADE, ESTADO) VALUES ('rua teste logradouro 1', '23049512', 'Rio de Janeiro', 'Rio de Janeiro');
INSERT INTO ENDERECO (LOGRADOURO, CEP, CIDADE, ESTADO) VALUES ('rua teste logradouro 2', '54123945', 'Porto Alegre', 'Rio Grande do Sul');
INSERT INTO ENDERECO (LOGRADOURO, CEP, CIDADE, ESTADO) VALUES ('rua teste logradouro 3', '41095421', 'São Paulo', 'São Paulo');
INSERT INTO ENDERECO (LOGRADOURO, CEP, CIDADE, ESTADO) VALUES ('rua teste logradouro 4', '31094132', 'Minas Gerais', 'Minas Gerais');


INSERT INTO HOTEL (NOME, ENDERECO_ID) VALUES ('HOTEL FIAP 1', 1);
INSERT INTO HOTEL (NOME, ENDERECO_ID) VALUES ('HOTEL FIAP 2', 2);
INSERT INTO HOTEL (NOME, ENDERECO_ID) VALUES ('HOTEL FIAP 3', 3);
INSERT INTO HOTEL (NOME, ENDERECO_ID) VALUES ('HOTEL FIAP 4', 4);

INSERT INTO AMENIDADE (NOME) VALUES ('1 x Piscina Adulto, aquecida e coberta');
INSERT INTO AMENIDADE (NOME) VALUES ('1 x Piscina Adulto, não aquecida em área aberta');
INSERT INTO AMENIDADE (NOME) VALUES ('1 x Piscina Infantil, aquecida e coberta');
INSERT INTO AMENIDADE (NOME) VALUES ('1 x Piscina Infantil, não aquecida em área aberta');
INSERT INTO AMENIDADE (NOME) VALUES ('2 x Restaurantes no estilo Self Service');
INSERT INTO AMENIDADE (NOME) VALUES ('1 x Restaurante a La Carte');
INSERT INTO AMENIDADE (NOME) VALUES ('1 x Área Kids, com brinquedoteca, vídeo games e biblioteca');
INSERT INTO AMENIDADE (NOME) VALUES ('Equipe de Entretenimento Infantil (diversas idades) e adulto');

INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (1,1);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (1,2);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (1,7);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (2,1);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (2,2);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (2,5);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (3,3);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (3,4);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (3,8);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (4,4);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (4,6);
INSERT INTO HOTEL_AMENIDADES(HOTEL_ID, AMENIDADE_ID) VALUES (4,8);


INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (1, 'PREDIO 1 HOTEL 1');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (1, 'PREDIO 2 HOTEL 1');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (2, 'PREDIO 1 HOTEL 2');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (2, 'PREDIO 2 HOTEL 2');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (2, 'PREDIO 3 HOTEL 2');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (3, 'PREDIO 1 HOTEL 3');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (3, 'PREDIO 2 HOTEL 3');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (4, 'PREDIO 1 HOTEL 4');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (4, 'PREDIO 2 HOTEL 4');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (4, 'PREDIO 3 HOTEL 4');
INSERT INTO PREDIO (HOTEL_ID, NOME) VALUES (4, 'PREDIO 4 HOTEL 4');


INSERT INTO MOVEL (NOME) VALUES ('1 x Sofá');
INSERT INTO MOVEL (NOME) VALUES ('2 x Poltronas');
INSERT INTO MOVEL (NOME) VALUES ('1 x Frigobar');
INSERT INTO MOVEL (NOME) VALUES ('1 x TV Led 54 pols');
INSERT INTO MOVEL (NOME) VALUES ('1 x Mesa de Escritório');
INSERT INTO MOVEL (NOME) VALUES ('1 x Cadeira de Escritório');
INSERT INTO MOVEL (NOME) VALUES ('1 x poltronas');
INSERT INTO MOVEL (NOME) VALUES ('1 x TV Led 62 pols');

INSERT INTO TIPO_QUARTO (NOME_TIPO, CAPACIDADE_TOTAL, QUANTIDADE_CAMAS, BANHEIRO) VALUES ('Standard Simples', 2, '1 x Queen Size', 'Simples (Box com Ducha, Privada, Ducha higiênica e pia com espelho)');
INSERT INTO TIPO_QUARTO (NOME_TIPO, CAPACIDADE_TOTAL, QUANTIDADE_CAMAS, BANHEIRO) VALUES ('Standard Duplo', 4, '1 x Queen Size e 2 x Solteiro', 'Simples (Box com Ducha, Privada, Ducha higiênica e pia com espelho)');
INSERT INTO TIPO_QUARTO (NOME_TIPO, CAPACIDADE_TOTAL, QUANTIDADE_CAMAS, BANHEIRO) VALUES ('Luxo Simples', 3, '1 x King Size', 'Luxo (Box com Ducha, Privada, Ducha higiênica e pia dupla com espelho)');
INSERT INTO TIPO_QUARTO (NOME_TIPO, CAPACIDADE_TOTAL, QUANTIDADE_CAMAS, BANHEIRO) VALUES ('Luxo Duplo', 4, '1 x King Size e 2 x Solteiro', 'Luxo (Box com Ducha, Privada, Ducha higiênica e pia dupla com espelho)');
INSERT INTO TIPO_QUARTO (NOME_TIPO, CAPACIDADE_TOTAL, QUANTIDADE_CAMAS, BANHEIRO) VALUES ('Premium Simples', 1, '1 x King Size', 'Premium (Box com Ducha, Privada, Ducha higiênica, pia dupla com espelho e Sauna)');
INSERT INTO TIPO_QUARTO (NOME_TIPO, CAPACIDADE_TOTAL, QUANTIDADE_CAMAS, BANHEIRO) VALUES ('Premium Duplo', 4, '2 x King Size', 'Premium (Box com Ducha, Privada, Ducha higiênica, pia dupla com espelho e Sauna)');


INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (1,1);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (1,2);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (1,3);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (1,4);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (1,5);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (1,6);

INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (2,1);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (2,7);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (2,3);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (2,4);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (2,5);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (2,6);

INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (3,1);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (3,2);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (3,3);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (3,4);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (3,5);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (3,6);

INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (4,1);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (4,7);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (4,3);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (4,8);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (4,5);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (4,6);


INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (5,1);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (5,7);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (5,3);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (5,8);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (5,5);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (5,6);

INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (6,1);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (6,7);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (6,3);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (6,8);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (6,5);
INSERT INTO TIPO_QUARTO_MOVEL (TIPO_QUARTO_ID, MOVEL_ID) VALUES (6,6);

INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,1,1,100.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,1,2,150.00,1);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,1,3,250.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,1,3,250.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,1,3,250.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,1,3,250.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,2,4,350.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,2,4,350.00,1);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (1,2,4,350.00,0);

INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,3,5,450.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,3,5,450.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,3,5,450.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,3,5,450.00,1);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,4,6,650.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,4,6,650.00,1);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,4,6,650.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,5,6,650.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (2,5,6,650.00,0);

INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (3,6,1,100.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (3,6,2,150.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (3,6,3,250.00,1);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (3,6,3,250.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (3,7,3,250.00,1);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (3,7,3,250.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (3,7,6,350.00,0);


INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,8,5,450.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,9,5,450.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,10,5,450.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,11,5,450.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,8,6,650.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,9,6,650.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,10,6,650.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,11,6,650.00,0);
INSERT INTO QUARTO (ID_HOTEL, PREDIO_ID, TIPO_QUARTO_ID, VALOR_DIARIA, STATUS) VALUES (4,8,6,650.00,0);


INSERT INTO SERVICO (NOME, VALOR) VALUES ('Café da Manhã', 65.00);
INSERT INTO SERVICO (NOME, VALOR) VALUES ('Almoço', 65.00);
INSERT INTO SERVICO (NOME, VALOR) VALUES ('Jantar', 85.00);
INSERT INTO SERVICO (NOME, VALOR) VALUES ('Massagem Completa', 25.00);
INSERT INTO SERVICO (NOME, VALOR) VALUES ('Manicure', 85.00);

INSERT INTO ITEM (NOME, VALOR) VALUES ('Refrigerantes', 9.00);
INSERT INTO ITEM (NOME, VALOR) VALUES ('Sucos', 13.00);
INSERT INTO ITEM (NOME, VALOR) VALUES ('Cervejas Nacionais', 15.00);
INSERT INTO ITEM (NOME, VALOR) VALUES ('Cervejas Importadas', 25.00);
INSERT INTO ITEM (NOME, VALOR) VALUES ('Caipirinhas', 35.00);

INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (1,1);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (1,2);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (1,3);

INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (2,1);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (2,2);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (2,4);

INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (3,1);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (3,2);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (3,3);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (3,4);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (3,5);

INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (4,3);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (4,1);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (4,2);
INSERT INTO HOTEL_ITENS (HOTEL_ID, ITEM_ID) VALUES (4,5);


INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (1,1);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (1,2);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (1,3);

INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (2,1);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (2,2);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (2,4);

INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (3,1);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (3,2);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (3,3);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (3,4);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (3,5);

INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (4,3);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (4,1);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (4,2);
INSERT INTO HOTEL_SERVICOS (HOTEL_ID, SERVICO_ID) VALUES (4,5);


INSERT INTO RESERVA (CLIENTE_ID, DATA_INICIAL, DATA_FINAL, QUANTIDADE_PESSOAS, VALOR_RESERVA, VALOR_TOTAL) VALUES (1, '2024-03-27', '2024-04-05', 4, 1000.00, 1110.00);

INSERT INTO RESERVA (CLIENTE_ID, DATA_INICIAL, DATA_FINAL, QUANTIDADE_PESSOAS, VALOR_RESERVA, VALOR_TOTAL) VALUES (2, '2024-10-05', '2024-10-25', 6, 4000.00, 4100.00);

INSERT INTO RESERVA (CLIENTE_ID, DATA_INICIAL, DATA_FINAL, QUANTIDADE_PESSOAS, VALOR_RESERVA, VALOR_TOTAL) VALUES (3, '2024-05-31', '2024-06-08', 2, 100.00, 100.00);

INSERT INTO RESERVA (CLIENTE_ID, DATA_INICIAL, DATA_FINAL, QUANTIDADE_PESSOAS, VALOR_RESERVA, VALOR_TOTAL) VALUES (4, '2024-11-12', '2024-11-22', 3, 2000.00, 2180.00);

INSERT INTO RESERVA (CLIENTE_ID, DATA_INICIAL, DATA_FINAL, QUANTIDADE_PESSOAS, VALOR_RESERVA, VALOR_TOTAL) VALUES (5, '2024-09-01', '2024-09-10', 4, 1220.00, 1250.00);

INSERT INTO RESERVA_QUARTO (RESERVA_ID, QUARTO_ID) VALUES (1,2);

INSERT INTO RESERVA_QUARTO (RESERVA_ID, QUARTO_ID) VALUES (2,18);
INSERT INTO RESERVA_QUARTO (RESERVA_ID, QUARTO_ID) VALUES (2,19);

INSERT INTO RESERVA_QUARTO (RESERVA_ID, QUARTO_ID) VALUES (3,19);

INSERT INTO RESERVA_QUARTO (RESERVA_ID, QUARTO_ID) VALUES (4,1);
INSERT INTO RESERVA_QUARTO (RESERVA_ID, QUARTO_ID) VALUES (4,10);

INSERT INTO RESERVA_QUARTO (RESERVA_ID, QUARTO_ID) VALUES (5,16);